<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
        <RootNamespace>Announcarr.Test.Utils.Extensions.StringExtensionsTests</RootNamespace>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <OutputType>Exe</OutputType>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector" Version="10.0.1" />
        <PackageReference Include="Shouldly" Version="4.3.0" />
        <PackageReference Include="xunit.v3" Version="4.0.0" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\..\Utils\Extensions\String\String.csproj" />
    </ItemGroup>

</Project>
